"""Morning briefing scheduler.

Sends a daily AI-generated briefing to the admin at a configurable time.
The briefing combines:
- Today's calendar events (iCloud or Google)
- Recent panel memory takeaways
- A short AI summary tying it all together

Uses Telegram HTML parse mode for rich formatting.
"""

import asyncio
import html
import logging
from datetime import datetime
from zoneinfo import ZoneInfo

logger = logging.getLogger(__name__)


def _e(text: str) -> str:
    """Escape text for Telegram HTML."""
    return html.escape(text)


async def _build_briefing(
    *,
    timezone_str: str,
    calendar_client,  # GoogleCalendarClient | ICloudCalendarClient | None
    ai_registry,  # AIRegistry
) -> str:
    """Build the morning briefing HTML text. Returned string is ready to send."""
    tz = ZoneInfo(timezone_str)
    now = datetime.now(tz)

    ru_weekdays = ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"]
    ru_months = ["", "января", "февраля", "марта", "апреля", "мая", "июня",
                 "июля", "августа", "сентября", "октября", "ноября", "декабря"]
    date_str = f"{ru_weekdays[now.weekday()]}, {now.day} {ru_months[now.month]}"

    parts: list[str] = [f"<b>🌅 Утренний брифинг — {_e(date_str)}</b>\n"]

    # ── Calendar events ────────────────────────────────────────────────────────
    calendar_block = ""
    if calendar_client is not None:
        try:
            today_events = await calendar_client.get_upcoming_events_summary(days=1)
            if today_events and today_events not in ("", "Нет запланированных событий на ближайшие дни."):
                calendar_block = today_events
                parts.append(f"<b>📅 Сегодня:</b>\n{_e(today_events)}\n")
            else:
                parts.append("📅 <i>Событий на сегодня нет.</i>\n")
        except Exception as e:
            logger.warning("Briefing: calendar fetch failed: %s", e)

    # ── Panel memories ─────────────────────────────────────────────────────────
    try:
        from claudebots.routers.panel import _panel_memories  # noqa: PLC0415
        recent_memories = _panel_memories[-5:] if _panel_memories else []
    except Exception:
        recent_memories = []

    memory_block = ""
    if recent_memories:
        parts.append("<b>🧠 Последние выводы панели:</b>")
        lines = []
        for mem in recent_memories:
            if isinstance(mem, dict):
                label = f"[{_e(mem['topic'])}] " if mem.get("topic") else ""
                lines.append(f"• {label}{_e(mem['text'])}")
            elif isinstance(mem, str):
                lines.append(f"• {_e(mem)}")
        memory_block = "\n".join(lines)
        parts.append(memory_block + "\n")

    # ── AI summary ─────────────────────────────────────────────────────────────
    ai_summary = ""
    used_provider = ""
    try:
        for provider_name in ("openrouter_gemini", "groq", "claude"):
            if ai_registry.has_provider(provider_name):
                client = ai_registry.get_client(provider_name)
                context_parts = []
                if calendar_block:
                    context_parts.append(f"События дня:\n{calendar_block}")
                if memory_block:
                    context_parts.append(f"Выводы прошлых обсуждений:\n{memory_block}")

                if not context_parts:
                    break

                prompt = (
                    "\n\n".join(context_parts) + "\n\n"
                    "Напиши утренний прогноз на день — 2-3 предложения на русском языке. "
                    "Что важно не забыть, что может быть актуально из прошлых обсуждений. "
                    "Живым языком. Только сам текст, без заголовков и пояснений."
                )
                ai_summary = await client.complete(
                    system=(
                        "Ты личный ассистент, помогаешь начать день продуктивно. "
                        "Отвечай ТОЛЬКО кратким текстом на русском языке — без мета-комментариев, "
                        "без пояснений задачи, без ссылок на контекст или инструкции. "
                        "Только сам текст брифинга."
                    ),
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=150,
                )
                ai_summary = ai_summary.strip()
                used_provider = provider_name
                break
    except Exception as e:
        logger.warning("Briefing: AI summary failed: %s", e)

    if ai_summary:
        parts.append(f"<blockquote>💬 {_e(ai_summary)}</blockquote>")

    if used_provider:
        logger.debug("Briefing AI summary generated by: %s", used_provider)

    return "\n".join(parts)


async def _briefing_loop(
    *,
    bot,  # Bot
    admin_user_id: int,
    timezone_str: str,
    briefing_time: str,
    calendar_client,
    ai_registry,
) -> None:
    """Send morning briefing at a fixed local time each day."""
    from claudebots.core.scheduling import daily_at

    tz = ZoneInfo(timezone_str)
    async for _ in daily_at(briefing_time, tz, label="Briefing scheduler", log=logger):
        try:
            text = await _build_briefing(
                timezone_str=timezone_str,
                calendar_client=calendar_client,
                ai_registry=ai_registry,
            )
            await bot.send_message(admin_user_id, text, parse_mode="HTML")
            logger.info("Morning briefing sent to admin")
        except asyncio.CancelledError:
            raise
        except Exception as e:
            logger.warning("Briefing send failed: %s", e)


def start_briefing_scheduler(
    *,
    bot,  # Bot
    admin_user_id: int,
    timezone_str: str,
    briefing_time: str,
    calendar_client,
    ai_registry,
) -> "asyncio.Task[None]":
    """Create and return the morning briefing background task."""
    task: asyncio.Task[None] = asyncio.create_task(
        _briefing_loop(
            bot=bot,
            admin_user_id=admin_user_id,
            timezone_str=timezone_str,
            briefing_time=briefing_time,
            calendar_client=calendar_client,
            ai_registry=ai_registry,
        )
    )
    task.add_done_callback(
        lambda t: logger.warning("Briefing loop raised: %s", t.exception())
        if not t.cancelled() and t.exception() else None
    )
    logger.info("Morning briefing scheduler started (time=%s %s)", briefing_time, timezone_str)
    return task
